services:

  postgres:
    image: postgres:18
    container_name: smarttrip-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: smarttrip
      POSTGRES_USER: smarttrip
      POSTGRES_PASSWORD: smarttrip

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U smarttrip -d smarttrip"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: