export const PLACE_CATEGORIES = {
  TOURIST_ATTRACTION: 'TOURIST_ATTRACTION',
  MUSEUM: 'MUSEUM',
  RESTAURANT: 'RESTAURANT',
  CAFE: 'CAFE',
  PARK: 'PARK'
} as const;

export type PlaceCategory =
  typeof PLACE_CATEGORIES[keyof typeof PLACE_CATEGORIES];